package com.voicerpg.android.combat

// GENERATED from docs/combat-design/data/movesets.json - regenerate, do not hand-edit.
data class EnemyMove(
    val name: String,
    val school: String,
    val kind: String,
    val powerMult: Float,
    val targetRule: String,
    val applyStatus: String? = null,
    val cooldownTurns: Int = 0,
    val weight: Int = 1,
    val summon: String? = null,
    val summonCount: Int = 0
)
data class PhaseRule(val hpBelow: Float, val addMoves: List<EnemyMove>, val note: String = "")
data class Moveset(val moves: List<EnemyMove>, val phases: List<PhaseRule> = emptyList())

object MovesetTable {
    val FALLBACK_BASIC = EnemyMove("Attack", "PHYSICAL", "BASIC", 1.0f, "SINGLE_RANDOM")
    val TABLE: Map<String, Moveset> = mapOf(
        "flesh_bruiser" to Moveset(listOf(EnemyMove("Cleave", "PHYSICAL", "BASIC", 1.0f, "SINGLE_RANDOM", applyStatus = null, cooldownTurns = 0, weight = 6, summon = null, summonCount = 0), EnemyMove("Savage Rip", "PHYSICAL", "HEAVY", 1.6f, "SINGLE_LOWEST_HP", applyStatus = "BLEED", cooldownTurns = 3, weight = 3, summon = null, summonCount = 0), EnemyMove("War Cry", "PHYSICAL", "BUFF", 0.0f, "SELF", applyStatus = "BLESS", cooldownTurns = 5, weight = 1, summon = null, summonCount = 0)), listOf()),
        "flesh_sniper" to Moveset(listOf(EnemyMove("Volley Shot", "PHYSICAL", "BASIC", 1.0f, "SINGLE_RANDOM", applyStatus = null, cooldownTurns = 0, weight = 7, summon = null, summonCount = 0), EnemyMove("Aimed Shot", "PHYSICAL", "HEAVY", 1.5f, "SINGLE_LOWEST_HP", applyStatus = null, cooldownTurns = 3, weight = 3, summon = null, summonCount = 0)), listOf()),
        "flesh_caster" to Moveset(listOf(EnemyMove("Hex Bolt", "SHADOW", "BASIC", 1.0f, "SINGLE_RANDOM", applyStatus = "CORRODE", cooldownTurns = 0, weight = 5, summon = null, summonCount = 0), EnemyMove("Mind Rake", "SHADOW", "AOE", 0.7f, "PARTY_AOE", applyStatus = "WEAKEN", cooldownTurns = 4, weight = 2, summon = null, summonCount = 0), EnemyMove("Siphon Life", "SHADOW", "DRAIN", 1.0f, "SINGLE_MARKED", applyStatus = null, cooldownTurns = 4, weight = 2, summon = null, summonCount = 0)), listOf()),
        "beast_sniper" to Moveset(listOf(EnemyMove("Skitter Bite", "PHYSICAL", "BASIC", 1.0f, "SINGLE_RANDOM", applyStatus = "BLEED", cooldownTurns = 0, weight = 6, summon = null, summonCount = 0), EnemyMove("Swarm Flurry", "PHYSICAL", "HEAVY", 1.4f, "SINGLE_RANDOM", applyStatus = null, cooldownTurns = 3, weight = 3, summon = null, summonCount = 0)), listOf()),
        "assassin_sniper" to Moveset(listOf(EnemyMove("Shiv", "SHADOW", "BASIC", 1.0f, "SINGLE_LOWEST_HP", applyStatus = null, cooldownTurns = 0, weight = 5, summon = null, summonCount = 0), EnemyMove("Backstab", "SHADOW", "HEAVY", 1.8f, "SINGLE_LOWEST_HP", applyStatus = "BLEED", cooldownTurns = 3, weight = 3, summon = null, summonCount = 0), EnemyMove("Venom Blade", "SHADOW", "BASIC", 1.0f, "SINGLE_RANDOM", applyStatus = "POISON", cooldownTurns = 2, weight = 2, summon = null, summonCount = 0)), listOf()),
        "undead_bruiser" to Moveset(listOf(EnemyMove("Rot Claw", "SHADOW", "BASIC", 1.0f, "SINGLE_RANDOM", applyStatus = "POISON", cooldownTurns = 0, weight = 6, summon = null, summonCount = 0), EnemyMove("Grave Chill", "CRYOMANCY", "HEAVY", 1.4f, "SINGLE_MARKED", applyStatus = "CHILL", cooldownTurns = 3, weight = 2, summon = null, summonCount = 0), EnemyMove("Bone Shield", "PHYSICAL", "BUFF", 0.0f, "SELF", applyStatus = "GUARD", cooldownTurns = 5, weight = 1, summon = null, summonCount = 0)), listOf()),
        "undead_sniper" to Moveset(listOf(EnemyMove("Bone Shot", "PHYSICAL", "BASIC", 1.0f, "SINGLE_RANDOM", applyStatus = null, cooldownTurns = 0, weight = 7, summon = null, summonCount = 0), EnemyMove("Gravewail", "SHADOW", "AOE", 0.6f, "PARTY_AOE", applyStatus = "CHILL", cooldownTurns = 4, weight = 2, summon = null, summonCount = 0)), listOf()),
        "undead_summoner" to Moveset(listOf(EnemyMove("Necrotic Bolt", "SHADOW", "BASIC", 1.0f, "SINGLE_RANDOM", applyStatus = "POISON", cooldownTurns = 0, weight = 4, summon = null, summonCount = 0), EnemyMove("Raise Restless", "SHADOW", "SUMMON", 0.0f, "SELF", applyStatus = null, cooldownTurns = 4, weight = 4, summon = "Silt Ghoul", summonCount = 0)), listOf()),
        "undead_caster" to Moveset(listOf(EnemyMove("Wither Touch", "SHADOW", "BASIC", 1.0f, "SINGLE_RANDOM", applyStatus = "POISON", cooldownTurns = 0, weight = 5, summon = null, summonCount = 0), EnemyMove("Dread Wail", "SHADOW", "AOE", 0.6f, "PARTY_AOE", applyStatus = "WEAKEN", cooldownTurns = 4, weight = 3, summon = null, summonCount = 0)), listOf()),
        "construct_bruiser" to Moveset(listOf(EnemyMove("Iron Slam", "PHYSICAL", "BASIC", 1.0f, "SINGLE_RANDOM", applyStatus = null, cooldownTurns = 0, weight = 6, summon = null, summonCount = 0), EnemyMove("Crush", "PHYSICAL", "HEAVY", 1.6f, "SINGLE_LOWEST_HP", applyStatus = null, cooldownTurns = 3, weight = 3, summon = null, summonCount = 0), EnemyMove("Steam Vent", "PYROMANCY", "AOE", 0.7f, "PARTY_AOE", applyStatus = "BURN", cooldownTurns = 4, weight = 2, summon = null, summonCount = 0)), listOf()),
        "construct_sniper" to Moveset(listOf(EnemyMove("Bolt Volley", "PHYSICAL", "BASIC", 1.0f, "SINGLE_RANDOM", applyStatus = null, cooldownTurns = 0, weight = 6, summon = null, summonCount = 0), EnemyMove("Suppressive Fire", "PHYSICAL", "AOE", 0.6f, "PARTY_AOE", applyStatus = null, cooldownTurns = 4, weight = 3, summon = null, summonCount = 0)), listOf()),
        "construct_caster" to Moveset(listOf(EnemyMove("Grinding Slab", "PHYSICAL", "BASIC", 1.0f, "SINGLE_RANDOM", applyStatus = null, cooldownTurns = 0, weight = 5, summon = null, summonCount = 0), EnemyMove("Sigil Pulse", "ELECTROMANCY", "AOE", 0.7f, "PARTY_AOE", applyStatus = "OVERLOAD", cooldownTurns = 5, weight = 2, summon = null, summonCount = 0)), listOf()),
        "verdant_bruiser" to Moveset(listOf(EnemyMove("Vine Lash", "NATURE", "BASIC", 1.0f, "SINGLE_RANDOM", applyStatus = null, cooldownTurns = 0, weight = 6, summon = null, summonCount = 0), EnemyMove("Root Grasp", "NATURE", "HEAVY", 1.3f, "SINGLE_MARKED", applyStatus = "ROOT", cooldownTurns = 3, weight = 3, summon = null, summonCount = 0), EnemyMove("Thorn Burst", "NATURE", "AOE", 0.6f, "PARTY_AOE", applyStatus = "BLEED", cooldownTurns = 5, weight = 2, summon = null, summonCount = 0)), listOf()),
        "verdant_sniper" to Moveset(listOf(EnemyMove("Spore Shot", "NATURE", "BASIC", 1.0f, "SINGLE_RANDOM", applyStatus = "POISON", cooldownTurns = 0, weight = 6, summon = null, summonCount = 0), EnemyMove("Snare Seed", "NATURE", "HEAVY", 1.2f, "SINGLE_LOWEST_HP", applyStatus = "ROOT", cooldownTurns = 4, weight = 2, summon = null, summonCount = 0)), listOf()),
        "verdant_caster" to Moveset(listOf(EnemyMove("Thorn Lash", "NATURE", "BASIC", 1.0f, "SINGLE_RANDOM", applyStatus = null, cooldownTurns = 0, weight = 5, summon = null, summonCount = 0), EnemyMove("Bramble Whip", "NATURE", "HEAVY", 1.2f, "SINGLE_RANDOM", applyStatus = "ROOT", cooldownTurns = 3, weight = 3, summon = null, summonCount = 0), EnemyMove("Choking Pollen", "NATURE", "AOE", 0.6f, "PARTY_AOE", applyStatus = "POISON", cooldownTurns = 4, weight = 3, summon = null, summonCount = 0)), listOf()),
        "void_wisp" to Moveset(listOf(EnemyMove("Drain Whisper", "SHADOW", "BASIC", 1.0f, "SINGLE_RANDOM", applyStatus = "CORRODE", cooldownTurns = 0, weight = 6, summon = null, summonCount = 0), EnemyMove("Huddle", "SHADOW", "AOE", 0.5f, "PARTY_AOE", applyStatus = null, cooldownTurns = 4, weight = 2, summon = null, summonCount = 0)), listOf()),
        "void_bruiser" to Moveset(listOf(EnemyMove("Tendril Rake", "SHADOW", "BASIC", 1.0f, "SINGLE_RANDOM", applyStatus = null, cooldownTurns = 0, weight = 6, summon = null, summonCount = 0), EnemyMove("Devour Shadow", "SHADOW", "DRAIN", 1.2f, "SINGLE_LOWEST_HP", applyStatus = null, cooldownTurns = 3, weight = 3, summon = null, summonCount = 0)), listOf()),
        "void_sniper" to Moveset(listOf(EnemyMove("Umbral Lance", "SHADOW", "BASIC", 1.0f, "SINGLE_RANDOM", applyStatus = null, cooldownTurns = 0, weight = 6, summon = null, summonCount = 0), EnemyMove("Silence Grip", "SHADOW", "HEAVY", 1.3f, "SINGLE_MARKED", applyStatus = "WEAKEN", cooldownTurns = 4, weight = 3, summon = null, summonCount = 0)), listOf()),
        "void_caster" to Moveset(listOf(EnemyMove("Void Bolt", "SHADOW", "BASIC", 1.0f, "SINGLE_RANDOM", applyStatus = "CORRODE", cooldownTurns = 0, weight = 5, summon = null, summonCount = 0), EnemyMove("Enveloping Dark", "SHADOW", "AOE", 0.7f, "PARTY_AOE", applyStatus = "WEAKEN", cooldownTurns = 5, weight = 3, summon = null, summonCount = 0), EnemyMove("Siphon Essence", "SHADOW", "DRAIN", 1.1f, "SINGLE_LOWEST_HP", applyStatus = null, cooldownTurns = 4, weight = 2, summon = null, summonCount = 0)), listOf()),
        "radiant_bruiser" to Moveset(listOf(EnemyMove("Gleaming Blow", "HOLY", "BASIC", 1.0f, "SINGLE_RANDOM", applyStatus = null, cooldownTurns = 0, weight = 6, summon = null, summonCount = 0), EnemyMove("Judgement", "HOLY", "HEAVY", 1.6f, "SINGLE_LOWEST_HP", applyStatus = null, cooldownTurns = 3, weight = 3, summon = null, summonCount = 0), EnemyMove("Consecrate", "HOLY", "AOE", 0.6f, "PARTY_AOE", applyStatus = "BURN", cooldownTurns = 5, weight = 2, summon = null, summonCount = 0)), listOf()),
        "radiant_caster" to Moveset(listOf(EnemyMove("Searing Ray", "HOLY", "BASIC", 1.0f, "SINGLE_RANDOM", applyStatus = null, cooldownTurns = 0, weight = 6, summon = null, summonCount = 0), EnemyMove("Radiant Nova", "HOLY", "AOE", 0.7f, "PARTY_AOE", applyStatus = null, cooldownTurns = 4, weight = 3, summon = null, summonCount = 0)), listOf()),
        "radiant_healer" to Moveset(listOf(EnemyMove("Smite", "HOLY", "BASIC", 1.0f, "SINGLE_RANDOM", applyStatus = null, cooldownTurns = 0, weight = 5, summon = null, summonCount = 0), EnemyMove("Mend Ally", "HOLY", "BUFF", 0.0f, "SELF", applyStatus = "BLESS", cooldownTurns = 3, weight = 4, summon = null, summonCount = 0)), listOf()),
        "silence_bruiser" to Moveset(listOf(EnemyMove("Hush", "SHADOW", "BASIC", 1.0f, "SINGLE_RANDOM", applyStatus = "WEAKEN", cooldownTurns = 0, weight = 6, summon = null, summonCount = 0), EnemyMove("Null Crush", "PHYSICAL", "HEAVY", 1.5f, "SINGLE_LOWEST_HP", applyStatus = null, cooldownTurns = 3, weight = 3, summon = null, summonCount = 0)), listOf()),
        "silence_sniper" to Moveset(listOf(EnemyMove("Silencing Shot", "PHYSICAL", "BASIC", 1.0f, "SINGLE_RANDOM", applyStatus = "WEAKEN", cooldownTurns = 0, weight = 6, summon = null, summonCount = 0), EnemyMove("Dampening Field", "SHADOW", "AOE", 0.5f, "PARTY_AOE", applyStatus = "WEAKEN", cooldownTurns = 4, weight = 3, summon = null, summonCount = 0)), listOf()),
        "silence_caster" to Moveset(listOf(EnemyMove("Void Dirge", "SHADOW", "AOE", 0.6f, "PARTY_AOE", applyStatus = "WEAKEN", cooldownTurns = 4, weight = 4, summon = null, summonCount = 0), EnemyMove("Hollow Word", "SHADOW", "BASIC", 1.0f, "SINGLE_MARKED", applyStatus = "CORRODE", cooldownTurns = 0, weight = 4, summon = null, summonCount = 0)), listOf()),
        "mirror_doppel" to Moveset(listOf(EnemyMove("Mimic Strike", "PHYSICAL", "BASIC", 1.0f, "SINGLE_RANDOM", applyStatus = null, cooldownTurns = 0, weight = 5, summon = null, summonCount = 0), EnemyMove("Echo Incantation", "ELECTROMANCY", "AOE", 0.7f, "PARTY_AOE", applyStatus = "WEAKEN", cooldownTurns = 4, weight = 3, summon = null, summonCount = 0)), listOf()),
        "shadow_knight" to Moveset(listOf(EnemyMove("Holy Cleave", "HOLY", "BASIC", 1.0f, "SINGLE_RANDOM", applyStatus = null, cooldownTurns = 0, weight = 5, summon = null, summonCount = 0), EnemyMove("Radiant Smite", "HOLY", "HEAVY", 1.4f, "SINGLE_LOWEST_HP", applyStatus = null, cooldownTurns = 3, weight = 3, summon = null, summonCount = 0), EnemyMove("Petrified Aegis", "HOLY", "BUFF", 0.0f, "SELF", applyStatus = "GUARD", cooldownTurns = 4, weight = 2, summon = null, summonCount = 0)), listOf()),
        "shadow_warden" to Moveset(listOf(EnemyMove("Briar Shot", "NATURE", "BASIC", 1.0f, "SINGLE_RANDOM", applyStatus = null, cooldownTurns = 0, weight = 5, summon = null, summonCount = 0), EnemyMove("Snare of Doubt", "NATURE", "HEAVY", 1.2f, "SINGLE_RANDOM", applyStatus = "ROOT", cooldownTurns = 3, weight = 3, summon = null, summonCount = 0), EnemyMove("Shadow Bloom", "NATURE", "BUFF", 0.0f, "SELF", applyStatus = "BLESS", cooldownTurns = 4, weight = 2, summon = null, summonCount = 0)), listOf()),
        "shadow_blade" to Moveset(listOf(EnemyMove("Shadow Slash", "SHADOW", "BASIC", 1.0f, "SINGLE_RANDOM", applyStatus = null, cooldownTurns = 0, weight = 5, summon = null, summonCount = 0), EnemyMove("Severing Cut", "SHADOW", "HEAVY", 1.5f, "SINGLE_LOWEST_HP", applyStatus = "BLEED", cooldownTurns = 3, weight = 3, summon = null, summonCount = 0), EnemyMove("Shadow Step", "SHADOW", "BASIC", 1.1f, "SINGLE_RANDOM", applyStatus = null, cooldownTurns = 2, weight = 2, summon = null, summonCount = 0)), listOf()),
        "shadow_invocator" to Moveset(listOf(EnemyMove("Arcane Bolt", "ELECTROMANCY", "BASIC", 1.0f, "SINGLE_RANDOM", applyStatus = null, cooldownTurns = 0, weight = 5, summon = null, summonCount = 0), EnemyMove("Forked Lightning", "ELECTROMANCY", "AOE", 0.7f, "PARTY_AOE", applyStatus = null, cooldownTurns = 4, weight = 3, summon = null, summonCount = 0), EnemyMove("Disrupt Pulse", "ELECTROMANCY", "HEAVY", 1.3f, "SINGLE_RANDOM", applyStatus = "WEAKEN", cooldownTurns = 3, weight = 2, summon = null, summonCount = 0)), listOf()),
        "boss_broodmother" to Moveset(listOf(EnemyMove("Bite", "PHYSICAL", "BASIC", 1.0f, "SINGLE_RANDOM", applyStatus = "POISON", cooldownTurns = 0, weight = 5, summon = null, summonCount = 0), EnemyMove("Spawn Hatchlings", "SHADOW", "SUMMON", 0.0f, "SELF", applyStatus = null, cooldownTurns = 3, weight = 5, summon = "Toxic Hatchling", summonCount = 2)), listOf(PhaseRule(0.5f, listOf(), "Enrages: +30% speed, spawns 3 instead of 2"))),
        "boss_behemoth" to Moveset(listOf(EnemyMove("Trample", "NATURE", "HEAVY", 1.6f, "SINGLE_LOWEST_HP", applyStatus = null, cooldownTurns = 0, weight = 4, summon = null, summonCount = 0), EnemyMove("Bog Quake", "PHYSICAL", "AOE", 0.8f, "PARTY_AOE", applyStatus = "OVERLOAD", cooldownTurns = 4, weight = 3, summon = null, summonCount = 0), EnemyMove("Bog Breath", "NATURE", "BASIC", 1.0f, "SINGLE_RANDOM", applyStatus = "POISON", cooldownTurns = 0, weight = 3, summon = null, summonCount = 0)), listOf(PhaseRule(0.35f, listOf(), "Rooted Fury: Root-grasp every other turn, +def"))),
        "boss_wyrm" to Moveset(listOf(EnemyMove("Tail Lash", "NATURE", "AOE", 0.8f, "PARTY_AOE", applyStatus = null, cooldownTurns = 0, weight = 4, summon = null, summonCount = 0), EnemyMove("Silt Breath", "NATURE", "HEAVY", 1.5f, "SINGLE_LOWEST_HP", applyStatus = "POISON", cooldownTurns = 3, weight = 3, summon = null, summonCount = 0), EnemyMove("Burrow", "PHYSICAL", "BUFF", 0.0f, "SELF", applyStatus = "GUARD", cooldownTurns = 6, weight = 1, summon = null, summonCount = 0)), listOf()),
        "boss_kaelen" to Moveset(listOf(EnemyMove("Executioner Cut", "PHYSICAL", "HEAVY", 1.7f, "SINGLE_LOWEST_HP", applyStatus = "BLEED", cooldownTurns = 2, weight = 5, summon = null, summonCount = 0), EnemyMove("Shadow Fan", "SHADOW", "AOE", 0.7f, "PARTY_AOE", applyStatus = "BLEED", cooldownTurns = 4, weight = 3, summon = null, summonCount = 0), EnemyMove("Blink Strike", "SHADOW", "BASIC", 1.1f, "SINGLE_RANDOM", applyStatus = null, cooldownTurns = 0, weight = 3, summon = null, summonCount = 0)), listOf(PhaseRule(0.4f, listOf(), "Death Rattle: gains extra turn every 3rd round"))),
        "boss_galahault" to Moveset(listOf(EnemyMove("Oathbreaker Smite", "HOLY", "HEAVY", 1.6f, "SINGLE_LOWEST_HP", applyStatus = null, cooldownTurns = 0, weight = 4, summon = null, summonCount = 0), EnemyMove("Dawn Judgment", "HOLY", "AOE", 0.8f, "PARTY_AOE", applyStatus = "BURN", cooldownTurns = 4, weight = 3, summon = null, summonCount = 0), EnemyMove("Petrified Aegis", "HOLY", "BUFF", 0.0f, "SELF", applyStatus = "GUARD", cooldownTurns = 5, weight = 2, summon = null, summonCount = 0)), listOf(PhaseRule(0.5f, listOf(), "Broken Vow: drops aegis, hits harder (mult +0.3), takes +50% shadow"))),
        "boss_nocturne" to Moveset(listOf(EnemyMove("Silent Kill", "SHADOW", "HEAVY", 1.9f, "SINGLE_LOWEST_HP", applyStatus = "BLEED", cooldownTurns = 2, weight = 5, summon = null, summonCount = 0), EnemyMove("Murder of Blades", "SHADOW", "AOE", 0.8f, "PARTY_AOE", applyStatus = "BLEED", cooldownTurns = 4, weight = 4, summon = null, summonCount = 0)), listOf(PhaseRule(0.6f, listOf(), "Vanishes: untargetable for 1 turn each phase step"))),
        "boss_ouros" to Moveset(listOf(EnemyMove("Gear Cleave", "PHYSICAL", "BASIC", 1.2f, "SINGLE_RANDOM", applyStatus = null, cooldownTurns = 0, weight = 4, summon = null, summonCount = 0), EnemyMove("Overdrive", "PHYSICAL", "HEAVY", 1.7f, "SINGLE_LOWEST_HP", applyStatus = null, cooldownTurns = 3, weight = 3, summon = null, summonCount = 0), EnemyMove("Bellow of Iron", "ELECTROMANCY", "AOE", 0.7f, "PARTY_AOE", applyStatus = "OVERLOAD", cooldownTurns = 5, weight = 3, summon = null, summonCount = 0)), listOf(PhaseRule(0.5f, listOf(), "Wind-down: Shock Nova hits all + self-repairs 8%/turn for 2 turns"))),
        "boss_vaelor" to Moveset(listOf(EnemyMove("Void Horn Blast", "SHADOW", "AOE", 0.8f, "PARTY_AOE", applyStatus = "WEAKEN", cooldownTurns = 4, weight = 4, summon = null, summonCount = 0), EnemyMove("Standard Charge", "PHYSICAL", "HEAVY", 1.6f, "SINGLE_LOWEST_HP", applyStatus = null, cooldownTurns = 0, weight = 4, summon = null, summonCount = 0), EnemyMove("Summon Spectral Legion", "SHADOW", "SUMMON", 0.0f, "SELF", applyStatus = null, cooldownTurns = 6, weight = 2, summon = "Spectral Reaper", summonCount = 1)), listOf()),
        "boss_leviathan" to Moveset(listOf(EnemyMove("Tidal Maw", "SHADOW", "HEAVY", 1.7f, "SINGLE_LOWEST_HP", applyStatus = "WEAKEN", cooldownTurns = 3, weight = 4, summon = null, summonCount = 0), EnemyMove("Drowning Silence", "SHADOW", "AOE", 0.8f, "PARTY_AOE", applyStatus = "WEAKEN", cooldownTurns = 4, weight = 4, summon = null, summonCount = 0), EnemyMove("Void Spawn", "SHADOW", "SUMMON", 0.0f, "SELF", applyStatus = null, cooldownTurns = 5, weight = 2, summon = "Void Tendril", summonCount = 1)), listOf()),
        "boss_malakor" to Moveset(listOf(EnemyMove("Nullifying Word", "SHADOW", "BASIC", 1.2f, "SINGLE_RANDOM", applyStatus = "WEAKEN", cooldownTurns = 0, weight = 4, summon = null, summonCount = 0), EnemyMove("Choir of Silence", "SHADOW", "AOE", 0.8f, "PARTY_AOE", applyStatus = "WEAKEN", cooldownTurns = 3, weight = 4, summon = null, summonCount = 0), EnemyMove("Sever Echo", "SHADOW", "HEAVY", 1.8f, "SINGLE_LOWEST_HP", applyStatus = "CORRODE", cooldownTurns = 4, weight = 2, summon = null, summonCount = 0)), listOf(PhaseRule(0.34f, listOf(), "Death of Voice (scripted, ONCE): total silence for 1 round; the party breaks it with the Primordial Incantation (single Transcendental 3x grant, then cleared - not every turn)."), PhaseRule(0.66f, listOf(), "Summons Echo Nullifiers (cap 4)"))),
    )
    fun movesetFor(id: String): Moveset? = TABLE[id]
}
