package com.voicerpg.engine.combat

import com.voicerpg.engine.content.GameContent
import com.voicerpg.engine.model.SpellGraphics

// GENERATED from docs/combat-design/data/movesets.json - regenerate, do not hand-edit.
data class EnemyMove(
    val name: String,
    val school: String,
    val kind: String,
    val powerMult: Float,
    val targetRule: String,
    val applyStatus: String? = null,
    val cooldownTurns: Int = 0,
    val weight: Int = 1,
    val summon: String? = null,
    val summonCount: Int = 0,
    val graphics: SpellGraphics? = null
)
data class PhaseRule(val hpBelow: Float, val addMoves: List<EnemyMove>, val note: String = "")
data class Moveset(val moves: List<EnemyMove>, val phases: List<PhaseRule> = emptyList())

object MovesetTable {
    val FALLBACK_BASIC = EnemyMove("Attack", "PHYSICAL", "BASIC", 1.0f, "SINGLE_RANDOM")
    val TABLE: Map<String, Moveset> = mapOf(
        "flesh_bruiser" to Moveset(listOf(EnemyMove("Cleave", "PHYSICAL", "BASIC", 1.0f, "SINGLE_RANDOM", applyStatus = null, cooldownTurns = 0, weight = 6, summon = null, summonCount = 0), EnemyMove("Savage Rip", "PHYSICAL", "HEAVY", 1.6f, "SINGLE_LOWEST_HP", applyStatus = "BLEED", cooldownTurns = 3, weight = 3, summon = null, summonCount = 0), EnemyMove("War Cry", "PHYSICAL", "BUFF", 0.0f, "SELF", applyStatus = "BLESS", cooldownTurns = 5, weight = 1, summon = null, summonCount = 0)), listOf()),
        "flesh_sniper" to Moveset(listOf(EnemyMove("Volley Shot", "PHYSICAL", "BASIC", 1.0f, "SINGLE_RANDOM", applyStatus = null, cooldownTurns = 0, weight = 7, summon = null, summonCount = 0), EnemyMove("Aimed Shot", "PHYSICAL", "HEAVY", 1.5f, "SINGLE_LOWEST_HP", applyStatus = null, cooldownTurns = 3, weight = 3, summon = null, summonCount = 0)), listOf()),
        "flesh_caster" to Moveset(listOf(EnemyMove("Hex Bolt", "SHADOW", "BASIC", 1.0f, "SINGLE_RANDOM", applyStatus = "CORRODE", cooldownTurns = 0, weight = 5, summon = null, summonCount = 0), EnemyMove("Mind Rake", "SHADOW", "AOE", 0.7f, "PARTY_AOE", applyStatus = "WEAKEN", cooldownTurns = 4, weight = 2, summon = null, summonCount = 0), EnemyMove("Siphon Life", "SHADOW", "DRAIN", 1.0f, "SINGLE_MARKED", applyStatus = null, cooldownTurns = 4, weight = 2, summon = null, summonCount = 0)), listOf()),
        "beast_sniper" to Moveset(listOf(EnemyMove("Skitter Bite", "PHYSICAL", "BASIC", 1.0f, "SINGLE_RANDOM", applyStatus = "BLEED", cooldownTurns = 0, weight = 6, summon = null, summonCount = 0), EnemyMove("Swarm Flurry", "PHYSICAL", "HEAVY", 1.4f, "SINGLE_RANDOM", applyStatus = null, cooldownTurns = 3, weight = 3, summon = null, summonCount = 0)), listOf()),
        "assassin_sniper" to Moveset(listOf(EnemyMove("Shiv", "SHADOW", "BASIC", 1.0f, "SINGLE_LOWEST_HP", applyStatus = null, cooldownTurns = 0, weight = 5, summon = null, summonCount = 0), EnemyMove("Backstab", "SHADOW", "HEAVY", 1.8f, "SINGLE_LOWEST_HP", applyStatus = "BLEED", cooldownTurns = 3, weight = 3, summon = null, summonCount = 0), EnemyMove("Venom Blade", "SHADOW", "BASIC", 1.0f, "SINGLE_RANDOM", applyStatus = "POISON", cooldownTurns = 2, weight = 2, summon = null, summonCount = 0)), listOf()),
        "undead_bruiser" to Moveset(listOf(EnemyMove("Rot Claw", "SHADOW", "BASIC", 1.0f, "SINGLE_RANDOM", applyStatus = "POISON", cooldownTurns = 0, weight = 6, summon = null, summonCount = 0), EnemyMove("Grave Chill", "CRYOMANCY", "HEAVY", 1.4f, "SINGLE_MARKED", applyStatus = "CHILL", cooldownTurns = 3, weight = 2, summon = null, summonCount = 0), EnemyMove("Bone Shield", "PHYSICAL", "BUFF", 0.0f, "SELF", applyStatus = "GUARD", cooldownTurns = 5, weight = 1, summon = null, summonCount = 0)), listOf()),
        "undead_sniper" to Moveset(listOf(EnemyMove("Bone Shot", "PHYSICAL", "BASIC", 1.0f, "SINGLE_RANDOM", applyStatus = null, cooldownTurns = 0, weight = 7, summon = null, summonCount = 0), EnemyMove("Gravewail", "SHADOW", "AOE", 0.6f, "PARTY_AOE", applyStatus = "CHILL", cooldownTurns = 4, weight = 2, summon = null, summonCount = 0)), listOf()),
        "undead_summoner" to Moveset(listOf(EnemyMove("Necrotic Bolt", "SHADOW", "BASIC", 1.0f, "SINGLE_RANDOM", applyStatus = "POISON", cooldownTurns = 0, weight = 4, summon = null, summonCount = 0), EnemyMove("Raise Restless", "SHADOW", "SUMMON", 0.0f, "SELF", applyStatus = null, cooldownTurns = 4, weight = 4, summon = "Template Minion", summonCount = 0)), listOf()),
        "undead_caster" to Moveset(listOf(EnemyMove("Wither Touch", "SHADOW", "BASIC", 1.0f, "SINGLE_RANDOM", applyStatus = "POISON", cooldownTurns = 0, weight = 5, summon = null, summonCount = 0), EnemyMove("Dread Wail", "SHADOW", "AOE", 0.6f, "PARTY_AOE", applyStatus = "WEAKEN", cooldownTurns = 4, weight = 3, summon = null, summonCount = 0)), listOf()),
        "construct_bruiser" to Moveset(listOf(EnemyMove("Iron Slam", "PHYSICAL", "BASIC", 1.0f, "SINGLE_RANDOM", applyStatus = null, cooldownTurns = 0, weight = 6, summon = null, summonCount = 0), EnemyMove("Crush", "PHYSICAL", "HEAVY", 1.6f, "SINGLE_LOWEST_HP", applyStatus = null, cooldownTurns = 3, weight = 3, summon = null, summonCount = 0), EnemyMove("Steam Vent", "PYROMANCY", "AOE", 0.7f, "PARTY_AOE", applyStatus = "BURN", cooldownTurns = 4, weight = 2, summon = null, summonCount = 0)), listOf()),
        "construct_sniper" to Moveset(listOf(EnemyMove("Bolt Volley", "PHYSICAL", "BASIC", 1.0f, "SINGLE_RANDOM", applyStatus = null, cooldownTurns = 0, weight = 6, summon = null, summonCount = 0), EnemyMove("Suppressive Fire", "PHYSICAL", "AOE", 0.6f, "PARTY_AOE", applyStatus = null, cooldownTurns = 4, weight = 3, summon = null, summonCount = 0)), listOf()),
        "construct_caster" to Moveset(listOf(EnemyMove("Grinding Slab", "PHYSICAL", "BASIC", 1.0f, "SINGLE_RANDOM", applyStatus = null, cooldownTurns = 0, weight = 5, summon = null, summonCount = 0), EnemyMove("Sigil Pulse", "ELECTROMANCY", "AOE", 0.7f, "PARTY_AOE", applyStatus = "OVERLOAD", cooldownTurns = 5, weight = 2, summon = null, summonCount = 0)), listOf()),
        "verdant_bruiser" to Moveset(listOf(EnemyMove("Vine Lash", "NATURE", "BASIC", 1.0f, "SINGLE_RANDOM", applyStatus = null, cooldownTurns = 0, weight = 6, summon = null, summonCount = 0), EnemyMove("Root Grasp", "NATURE", "HEAVY", 1.3f, "SINGLE_MARKED", applyStatus = "ROOT", cooldownTurns = 3, weight = 3, summon = null, summonCount = 0), EnemyMove("Thorn Burst", "NATURE", "AOE", 0.6f, "PARTY_AOE", applyStatus = "BLEED", cooldownTurns = 5, weight = 2, summon = null, summonCount = 0)), listOf()),
        "verdant_sniper" to Moveset(listOf(EnemyMove("Spore Shot", "NATURE", "BASIC", 1.0f, "SINGLE_RANDOM", applyStatus = "POISON", cooldownTurns = 0, weight = 6, summon = null, summonCount = 0), EnemyMove("Snare Seed", "NATURE", "HEAVY", 1.2f, "SINGLE_LOWEST_HP", applyStatus = "ROOT", cooldownTurns = 4, weight = 2, summon = null, summonCount = 0)), listOf()),
        "verdant_caster" to Moveset(listOf(EnemyMove("Thorn Lash", "NATURE", "BASIC", 1.0f, "SINGLE_RANDOM", applyStatus = null, cooldownTurns = 0, weight = 5, summon = null, summonCount = 0), EnemyMove("Bramble Whip", "NATURE", "HEAVY", 1.2f, "SINGLE_RANDOM", applyStatus = "ROOT", cooldownTurns = 3, weight = 3, summon = null, summonCount = 0), EnemyMove("Choking Pollen", "NATURE", "AOE", 0.6f, "PARTY_AOE", applyStatus = "POISON", cooldownTurns = 4, weight = 3, summon = null, summonCount = 0)), listOf()),
        "void_wisp" to Moveset(listOf(EnemyMove("Drain Whisper", "SHADOW", "BASIC", 1.0f, "SINGLE_RANDOM", applyStatus = "CORRODE", cooldownTurns = 0, weight = 6, summon = null, summonCount = 0), EnemyMove("Huddle", "SHADOW", "AOE", 0.5f, "PARTY_AOE", applyStatus = null, cooldownTurns = 4, weight = 2, summon = null, summonCount = 0)), listOf()),
        "void_bruiser" to Moveset(listOf(EnemyMove("Tendril Rake", "SHADOW", "BASIC", 1.0f, "SINGLE_RANDOM", applyStatus = null, cooldownTurns = 0, weight = 6, summon = null, summonCount = 0), EnemyMove("Devour Shadow", "SHADOW", "DRAIN", 1.2f, "SINGLE_LOWEST_HP", applyStatus = null, cooldownTurns = 3, weight = 3, summon = null, summonCount = 0)), listOf()),
        "void_sniper" to Moveset(listOf(EnemyMove("Umbral Lance", "SHADOW", "BASIC", 1.0f, "SINGLE_RANDOM", applyStatus = null, cooldownTurns = 0, weight = 6, summon = null, summonCount = 0), EnemyMove("Silence Grip", "SHADOW", "HEAVY", 1.3f, "SINGLE_MARKED", applyStatus = "WEAKEN", cooldownTurns = 4, weight = 3, summon = null, summonCount = 0)), listOf()),
        "void_caster" to Moveset(listOf(EnemyMove("Void Bolt", "SHADOW", "BASIC", 1.0f, "SINGLE_RANDOM", applyStatus = "CORRODE", cooldownTurns = 0, weight = 5, summon = null, summonCount = 0), EnemyMove("Enveloping Dark", "SHADOW", "AOE", 0.7f, "PARTY_AOE", applyStatus = "WEAKEN", cooldownTurns = 5, weight = 3, summon = null, summonCount = 0), EnemyMove("Siphon Essence", "SHADOW", "DRAIN", 1.1f, "SINGLE_LOWEST_HP", applyStatus = null, cooldownTurns = 4, weight = 2, summon = null, summonCount = 0)), listOf()),
        "radiant_bruiser" to Moveset(listOf(EnemyMove("Gleaming Blow", "HOLY", "BASIC", 1.0f, "SINGLE_RANDOM", applyStatus = null, cooldownTurns = 0, weight = 6, summon = null, summonCount = 0), EnemyMove("Judgement", "HOLY", "HEAVY", 1.6f, "SINGLE_LOWEST_HP", applyStatus = null, cooldownTurns = 3, weight = 3, summon = null, summonCount = 0), EnemyMove("Consecrate", "HOLY", "AOE", 0.6f, "PARTY_AOE", applyStatus = "BURN", cooldownTurns = 5, weight = 2, summon = null, summonCount = 0)), listOf()),
        "radiant_caster" to Moveset(listOf(EnemyMove("Searing Ray", "HOLY", "BASIC", 1.0f, "SINGLE_RANDOM", applyStatus = null, cooldownTurns = 0, weight = 6, summon = null, summonCount = 0), EnemyMove("Radiant Nova", "HOLY", "AOE", 0.7f, "PARTY_AOE", applyStatus = null, cooldownTurns = 4, weight = 3, summon = null, summonCount = 0)), listOf()),
        "radiant_healer" to Moveset(listOf(EnemyMove("Smite", "HOLY", "BASIC", 1.0f, "SINGLE_RANDOM", applyStatus = null, cooldownTurns = 0, weight = 5, summon = null, summonCount = 0), EnemyMove("Mend Ally", "HOLY", "BUFF", 0.0f, "SELF", applyStatus = "BLESS", cooldownTurns = 3, weight = 4, summon = null, summonCount = 0)), listOf()),
        "silence_bruiser" to Moveset(listOf(EnemyMove("Hush", "SHADOW", "BASIC", 1.0f, "SINGLE_RANDOM", applyStatus = "WEAKEN", cooldownTurns = 0, weight = 6, summon = null, summonCount = 0), EnemyMove("Null Crush", "PHYSICAL", "HEAVY", 1.5f, "SINGLE_LOWEST_HP", applyStatus = null, cooldownTurns = 3, weight = 3, summon = null, summonCount = 0)), listOf()),
        "silence_sniper" to Moveset(listOf(EnemyMove("Silencing Shot", "PHYSICAL", "BASIC", 1.0f, "SINGLE_RANDOM", applyStatus = "WEAKEN", cooldownTurns = 0, weight = 6, summon = null, summonCount = 0), EnemyMove("Dampening Field", "SHADOW", "AOE", 0.5f, "PARTY_AOE", applyStatus = "WEAKEN", cooldownTurns = 4, weight = 3, summon = null, summonCount = 0)), listOf()),
        "silence_caster" to Moveset(listOf(EnemyMove("Void Dirge", "SHADOW", "AOE", 0.6f, "PARTY_AOE", applyStatus = "WEAKEN", cooldownTurns = 4, weight = 4, summon = null, summonCount = 0), EnemyMove("Hollow Word", "SHADOW", "BASIC", 1.0f, "SINGLE_MARKED", applyStatus = "CORRODE", cooldownTurns = 0, weight = 4, summon = null, summonCount = 0)), listOf()),
        "mirror_doppel" to Moveset(listOf(EnemyMove("Mimic Strike", "PHYSICAL", "BASIC", 1.0f, "SINGLE_RANDOM", applyStatus = null, cooldownTurns = 0, weight = 5, summon = null, summonCount = 0), EnemyMove("Echo Incantation", "ELECTROMANCY", "AOE", 0.7f, "PARTY_AOE", applyStatus = "WEAKEN", cooldownTurns = 4, weight = 3, summon = null, summonCount = 0)), listOf()),
        "boss_template" to Moveset(listOf(EnemyMove("Crushing Blow", "PHYSICAL", "BASIC", 1.2f, "SINGLE_RANDOM", applyStatus = null, cooldownTurns = 0, weight = 4, summon = null, summonCount = 0), EnemyMove("Heavy Slam", "PHYSICAL", "HEAVY", 1.7f, "SINGLE_LOWEST_HP", applyStatus = null, cooldownTurns = 3, weight = 3, summon = null, summonCount = 0), EnemyMove("Shockwave", "PHYSICAL", "AOE", 0.8f, "PARTY_AOE", applyStatus = "WEAKEN", cooldownTurns = 4, weight = 3, summon = null, summonCount = 0), EnemyMove("Cataclysm", "PHYSICAL", "AOE", 2.4f, "PARTY_AOE", applyStatus = "OVERLOAD", cooldownTurns = 5, weight = 2, summon = null, summonCount = 0)), listOf(PhaseRule(0.66f, listOf(), "Enrages: summons reinforcements"), PhaseRule(0.33f, listOf(), "Overload: cataclysmic party-wide pressure"))),
    )
    fun movesetFor(id: String): Moveset? = com.voicerpg.engine.content.GameContent.movesetById(id) ?: TABLE[id]
}
